<?xml version='1.0' encoding="UTF-8"?>
<!DOCTYPE dat [
<!ELEMENT dat (meta,game*)>
	<!ELEMENT meta (description,version,time,generatedBy)>
	<!ELEMENT description EMPTY>
		<!ATTLIST description name CDATA #IMPLIED>
	<!ELEMENT version EMPTY>
		<!ATTLIST version name CDATA #IMPLIED>
	<!ELEMENT time EMPTY>
		<!ATTLIST time name CDATA #IMPLIED>
	<!ELEMENT generatedBy EMPTY>
		<!ATTLIST generatedBy name CDATA #IMPLIED>
	<!ELEMENT game (miscDetails,label*,player+)>
		<!ATTLIST game romname CDATA #IMPLIED>
		<!ATTLIST game gamename CDATA #IMPLIED>
		<!ATTLIST game numPlayers CDATA #IMPLIED>
		<!ATTLIST game alternating CDATA #IMPLIED>
		<!ATTLIST game mirrored CDATA #IMPLIED>
		<!ATTLIST game usesService CDATA #IMPLIED>
		<!ATTLIST game tilt CDATA #IMPLIED>
		<!ATTLIST game cocktail CDATA #IMPLIED>
	<!ELEMENT miscDetails (#PCDATA)>
	<!ELEMENT label EMPTY>
		<!ATTLIST label name CDATA #IMPLIED>
		<!ATTLIST label value CDATA #IMPLIED>
	<!ELEMENT player (controls*,labels*)>
		<!ATTLIST player number CDATA #IMPLIED>
		<!ATTLIST player numButtons CDATA #IMPLIED>
	<!ELEMENT controls (control*)>
	<!ELEMENT labels (label*)>
	<!ELEMENT control  (constant*,button*)>
		<!ATTLIST control name CDATA #IMPLIED>
	<!ELEMENT constant EMPTY>
		<!ATTLIST constant name CDATA #IMPLIED>
	<!ELEMENT button EMPTY>
		<!ATTLIST button name CDATA #IMPLIED>
]>
<dat>
	<meta>
		<description name="Controls.dat XML file"/>
		<version name="0.141.1"/>
		<time name="2011-01-05 18:17:26"/>
		<generatedBy name="SirPoonga"/>
	</meta>

	<game romname="88games" gamename="&apos;88 Games" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
This is a 4 player team type game where 2 players compete each time
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="Just Buttons">
					<constant name="button"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Run"/>
				<label name="P1_BUTTON2" value="Jump"/>
				<label name="P1_BUTTON3" value="Run"/>
			</labels>
		</player>
	</game>
	<game romname="005" gamename="005" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="4-way Joystick">
					<constant name="joy4way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="10yardj" gamename="10-Yard Fight (Japan)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Pass / Hike"/>
				<label name="P1_BUTTON2" value="Lateral"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="gtmr" gamename="1000 Miglia: Great 1000 Miles Rally (94/07/18)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="1" cocktail="1">
		<miscDetails>
IMPORTANT NOTE:  This game has several options regarding the control type.  It has an optional brake pedal/button as well as the option to play the game with either a 270 wheel or an 8way joystick.  The controls shown here are the ones used on the dedicated model.  Notice the lack of the brake pedal.  It seems that the brake pedal was used in conversion kits as the dedicated cabinet didn&apos;t have one.
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="270 Steering Wheel">
					<constant name="paddle"/>
				</control>
				<control name="Pedal (Microswitch)">
					<constant name="button"/>
					<button name="P1_BUTTON1"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Accelerate"/>
				<label name="P1_PADDLE" value="Left"/>
				<label name="P1_PADDLE_EXT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="1941" gamename="1941: Counter Attack (World)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Loop"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="1942" gamename="1942 (Revision B)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Loop"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="1943kai" gamename="1943 Kai: Midway Kaisen (Japan)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
A - Fire, B - Bomb Pressing both buttons will allow the plane to loop
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="A"/>
				<label name="P1_BUTTON2" value="B"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="1943" gamename="1943: The Battle of Midway (Euro)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
Press both buttons together to cause the plane to loop.
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Special"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="1944" gamename="1944: The Loop Master (USA 000620)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Shoot"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="19xx" gamename="19XX: The War Against Destiny (USA 951207)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
If you hold down the shoot button, your weapon powers up and gives you a homing missle in addition to you normal weapon.
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Shoot"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="openice" gamename="2 On 2 Open Ice Challenge (rev 1.21)" numPlayers="4" alternating="0" mirrored="1" usesService="0" tilt="1" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Turbo"/>
				<label name="P1_BUTTON2" value="Shoot / Block"/>
				<label name="P1_BUTTON3" value="Pass / Steal"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="39in1" gamename="39 in 1 MAME bootleg" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
This is a bootleg pcb that contains many classic vertical arcade games.  Because of this the &apos;alternating play&apos; flag is invalid and will vary from game to game.  The game kit is a pcb only and thus lacks any official labels.  The manual for this version lists the buttons as 1P-S1 thru 2P-S3.  However, these are simply the jamma pinouts.  Every control panel overlay manufacturer that has since released a overlay for this unit has either left the labels blank or labeled them A, B and C respectively. 
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="A"/>
				<label name="P1_BUTTON2" value="B"/>
				<label name="P1_BUTTON3" value="C"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="4enraya" gamename="4 En Raya" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="2-way Joystick (Horizontal)">
					<constant name="joy2way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Down"/>
				<label name="P1_BUTTON2" value="Shot"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="4in1" gamename="4 Fun in 1" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="4dwarrio" gamename="4-D Warriors (315-5162)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
			</labels>
		</player>
	</game>
	<game romname="64street" gamename="64th. Street - A Detective Story (World)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Pressing both buttons will do a special attack
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Attack"/>
				<label name="P1_BUTTON2" value="Jump"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="720" gamename="720 Degrees (rev 4)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
OTHER: The 720 controller is unique.  It is an optical sensed spinner with a joystick handle.  The controller had two encoder wheels on the same axis; one was like a normal spinner encode wheel with 72 spokes &amp; 72 gaps, the other encoder wheel had only two gaps spaced as far as alternating gaps on the normal encoder wheel (ie: instead of gap, spoke, gap, spoke, gap like on the normal wheel, the middle gap was part of the one fat spoke seperating the two gaps on the ends).  The normal encoder wheel turns the character in the game, the other encoder wheel is to help keep the stick calibrated with the screen, on each rotation of the stick. Mame only emulates the normal wheel as a dial type input; the other is ignored.  The character in the game can face 16 directions: the 4 cardinal directions, the 4 normal diagonals, and the 8 directions inbetween the cardinals and the diagonals.  The Kick button makes the character skate faster (in case that&apos;s not clear).  Both buttons are mirrored on opposite sides of the &apos;joystick&apos; spinner, but like most mirror cases, they are wired as a total of only two buttons.
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="Spinner">
					<constant name="dial"/>
				</control>
				<control name="Misc">
					<constant name="other"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Kick"/>
				<label name="P1_BUTTON2" value="Jump"/>
				<label name="P1_DIAL_EXT" value="Rotate Right"/>
				<label name="P1_DIAL" value="Rotate Left"/>
			</labels>
		</player>
	</game>
	<game romname="7jigen" gamename="7jigen no Youseitachi - Mahjong 7 Dimensions (Japan)" numPlayers="1" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Mahjong games are NOT compatable with ctrlr files.  As a matter of fact they pretty much all have the same layout and all have the same controls.  The controls are hardcoded, so remapping isn&apos;t reccomended, especially considering the fact that a full keyboard of buttons are required to play. 
		</miscDetails>
		<player number="1" numButtons="0">
			<controls>
				<control name="Mahjong Control Panel">
					<constant name="other"/>
				</control>
			</controls>
		<labels>
			</labels>
		</player>
	</game>
	<game romname="ace" gamename="Ace" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
The 2-way horizontal stick is a trigger stick, pushing left rotates the plane anticlockwise, pushing right rotates the plane clockwise
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="2-way Joystick (Horizontal)">
					<constant name="joy2way"/>
					<button name="P1_BUTTON1"/>
				</control>
				<control name="2-way Joystick (Vertical)">
					<constant name="vjoy2way"/>
				</control>
				<control name="Misc">
					<constant name="other"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
				<label name="P1_JOYSTICK_UP" value="Speed Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Slow Down"/>
			</labels>
		</player>
	</game>
	<game romname="acrobatm" gamename="Acrobat Mission" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Hold down Fire button to increase power
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="actfancr" gamename="Act-Fancer Cybernetick Hyper Weapon (World revision 2)" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Jump"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="hatena" gamename="Adventure Quiz 2 Hatena Hatena no Dai-Bouken (Japan 900228)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="4">
			<controls>
				<control name="Trivia Buttons">
					<constant name="button"/>
					<button name="P1_BUTTON1"/>
					<button name="P1_BUTTON2"/>
					<button name="P1_BUTTON3"/>
					<button name="P1_BUTTON4"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="1"/>
				<label name="P1_BUTTON2" value="2"/>
				<label name="P1_BUTTON3" value="3"/>
				<label name="P1_BUTTON4" value="4"/>
			</labels>
		</player>
	</game>
	<game romname="aerofgt" gamename="Aero Fighters" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Pressing bomb button drops bomb and plane also loops. There are no labels on the CP.
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="aburner2" gamename="After Burner II" numPlayers="1" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
The &apos;unknown&apos; button is emulated in MAME but has no real purpose.  As far as I can tell from the drivers, it was used for some sort of feedback in the simulation cockpits.
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="Flightstick (Analog)">
					<constant name="stick"/>
					<button name="P1_BUTTON1"/>
					<button name="P1_BUTTON2"/>
				</control>
				<control name="Throttle (Stick)">
					<constant name="stickz"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Vulcan"/>
				<label name="P1_BUTTON3" value="Unknown"/>
				<label name="P1_AD_STICK_Y_EXT" value="Down"/>
				<label name="P1_AD_STICK_Y" value="Up"/>
				<label name="P1_AD_STICK_X_EXT" value="Right"/>
				<label name="P1_AD_STICK_X" value="Left"/>
				<label name="P1_AD_STICK_Z" value="Slow"/>
				<label name="P1_AD_STICK_Z_EXT" value="Fast"/>
			</labels>
		</player>
	</game>
	<game romname="koshien" gamename="Ah Eikou no Koshien (Japan)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="1" cocktail="0">
		<miscDetails>
A - Power-up B - Hit/Throw C - Unknown action during game 
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="A"/>
				<label name="P1_BUTTON2" value="B"/>
				<label name="P1_BUTTON3" value="C"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="airbustr" gamename="Air Buster: Trouble Specialty Raid Unit (World)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Only 1 button on the CP but Mame has 2 mapped (both doing the same thing)
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Fire"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="airduel" gamename="Air Duel (Japan)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
Pinout shows 3 buttons (Fire1, Fire2, Fire3), the flyer shows 2 buttons, Mame has 4 buttons mapped and only 2 seem to work
		</miscDetails>
		<player number="1" numButtons="4">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Gun"/>
				<label name="P1_BUTTON2" value="Guided Bomb"/>
				<label name="P1_BUTTON3" value="Unknown"/>
				<label name="P1_BUTTON4" value="Unknown"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
			</labels>
		</player>
	</game>
	<game romname="airwolf" gamename="Airwolf" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
Button 2 acts differently based on the position on the screen.  In the lower half of the screen button 2 will shoot diagonally down to the ground.  In the top half it will drop a bomb
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Bomb"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="ajax" gamename="Ajax" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Machine Gun"/>
				<label name="P1_BUTTON2" value="Missle"/>
				<label name="P1_BUTTON3" value="Super Weapon"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="alexkidd" gamename="Alex Kidd: The Lost Stars (set 2, unprotected)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
I cold not find what the 3rd button did nor did I immediately notice where it is written in the driver (I think it&apos;s one of those generic drivers)
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Attack"/>
				<label name="P1_BUTTON2" value="Jump"/>
				<label name="P1_BUTTON3" value="Unknown"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="alibaba" gamename="Ali Baba and 40 Thieves" numPlayers="2" alternating="1" mirrored="1" usesService="0" tilt="0" cocktail="1">
		<miscDetails>
Drop is not the button label (couldn&apos;t find one).  It drops something behind your character which blocks the path of the Captain Thief which allows you to get away
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="4-way Joystick">
					<constant name="joy4way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Drop"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="astorm" gamename="Alien Storm (World, 2 Players, FD1094 317-0154)" numPlayers="3" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Attack"/>
				<label name="P1_BUTTON2" value="Roll"/>
				<label name="P1_BUTTON3" value="Special"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="aliensyn" gamename="Alien Syndrome (set 4, System 16B, unprotected)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="1">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Right"/>
			</labels>
		</player>
	</game>
	<game romname="avsp" gamename="Alien vs. Predator (Euro 940520)" numPlayers="3" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
The default dipswitch is two player mode; you need to F2 into the game&apos;s service mode and change it to three player mode to play with 3 players.  Each character has special moves.
		</miscDetails>
		<player number="1" numButtons="3">
			<controls>
				<control name="8-way Joystick">
					<constant name="joy8way"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Shoot"/>
				<label name="P1_BUTTON2" value="Attack"/>
				<label name="P1_BUTTON3" value="Jump (Dash)"/>
				<label name="P1_JOYSTICK_UP" value="Up"/>
				<label name="P1_JOYSTICK_DOWN" value="Down"/>
				<label name="P1_JOYSTICK_LEFT" value="Move Left"/>
				<label name="P1_JOYSTICK_RIGHT" value="Move Right"/>
			</labels>
		</player>
	</game>
	<game romname="alien3" gamename="Alien3: The Gun (World)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
There isn&apos;t much info about the &apos;real&apos; name for the second button on the guns.  If you have any info feel free to corect.  
		</miscDetails>
		<player number="1" numButtons="2">
			<controls>
				<control name="Analog Gun">
					<constant name="lightgun"/>
				</control>
			</controls>
		<labels>
				<label name="P1_BUTTON1" value="Fire"/>
				<label name="P1_BUTTON2" value="Secondary Weapon"/>
				<label name="P1_LIGHTGUN_X" value="Left"/>
				<label name="P1_LIGHTGUN_X_EXT" value="Right"/>
				<label name="P1_LIGHTGUN_Y" value="Up"/>
				<label name="P1_LIGHTGUN_Y_EXT" value="Down"/>
			</labels>
		</player>
	</game>
	<game romname="aliens" gamename="Aliens (World set 1)" numPlayers="2" alternating="0" mirrored="1" usesService="0" tilt="0" cocktail="0">
		<miscDetails>
		</miscDetails>
		<player number="1" numButtons="2">